name: 'nextcloud-with-memories'
services:
  nextcloud:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./custom_apps:/var/www/html/custom_apps:rw
      - ../:/var/www/html/custom_apps/memories:rw
      - ./config:/var/www/html/config:rw
      - ./data:/var/www/html/data:rw
    ports:
      - 9080:80
    image: nextcloud
